### PR TITLE
Command line errors have been resolved - argue() has been reintegrated.

### LINKED ISSUE #31: Command line integration causing problems for other use cases
With the command line integration being added to the main branch the program no longer works, unless you give it --xmin, --xmax, --tmin, --tmax. 
Not only does this make things more difficult for the end user, as they should not have to specify anything they don't want to, but it will also likely cause issues when using the program as a module.

Is there any way to solve this? 
Would it be possible to have the command line section as a separate file that calls solving_tdse.py as a module, or something similar?

### PR DESCRIPTION
**Pull request by AlexVernis**
There might be conflicts with new code, not sure how things might mesh. But it's running fine for me, so...

### CODE REVIEW

**Comment by dascroft** [comment]
This is taking its time isn't it. Usually its pretty quick when Its checking the merge.

**Comment by AlexVernis** [comment]
oh, there we are

**Comment by dascroft** [comment]
Merge it!

**Comment by AlexVernis** [comment]
im nervous.

**Comment by dascroft** [comment]
Well we can always revert if we need to, that's the best thing about github

**Comment by AlexVernis** [comment]
i am sweating Bullets.

**Comment by dascroft** [comment]
Now get some sleep, my email notifications can't take it lol

**Pull request merged**
