### PR TITLE
Squarewave Functionality

### PR DESCRIPTION
**Pull request by AlexVernis**
Added squarewave functionality to tdsesolver.py, adjusted an error message. Adjusted help command to be more informative.

### CODE REVIEW

**Comment by dascroft** [comment]
Merging

**Comment by AlexBradley0** [comment]
Why has stuff for squarewaves been added to "tdsesolver.py"?
I'm under the impression our main code for this is in "solving_tdse.py", "tdsesolver.py" is quite outdated compared out what I believe is our main one. If it should have been added to "tdsesolver.py" should I stop working to add squarewaves to "solving_tdse.py"?

**Comment by AlexVernis** [comment]
solving_tdse.py isn't command line compatible yet. At least not that I can see.

**Comment by dascroft** [comment]
Yes, that code is baseline code and should be moved to the new tdsesolver.py. Regarding solving_tdse.py, do you mean the functional forms variant or the classes version as since TrueEnder has said, that is not comline compatible yet.

**Pull request merged**
